spring.application.name=demo
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
server.port=8080
# Sửa lại URL trỏ lên server của SmarterASP.NET
spring.datasource.url=jdbc:sqlserver://SQL1002.site4now.net;databaseName=db_ac9276_schoolmanager;encrypt=true;trustServerCertificate=true;

# Điền tài khoản và mật khẩu
spring.datasource.username=db_ac9276_schoolmanager_admin
spring.datasource.password=${DB_PASSWORD}

# Các phần này giữ nguyên
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=

# spring.datasource.url=jdbc:sqlserver://DESKTOP-R8J6D5M\\MSSQLSERVER1:1433;encrypt=true;trustServerCertificate=true;databaseName=schoolmanager
# spring.datasource.username=sa
# spring.datasource.password=123123
# spring.datasource.url=jdbc:sqlserver://den1.mssql7.gear.host:1433;encrypt=true;trustServerCertificate=true;databaseName=school123456
# spring.datasource.username=school123456
# spring.datasource.password=Tf1XN700~Y!T
spring.jpa.show-sql=true
# Hibernate can detect SQL Server dialect automatically
app.jwt.secret=f31a6377-a7f1-4d51-a00c-c64b8774573a
app.jwt.expiration=86400000
